### ISSUE TITLE
showOverNavigation not working on home page

### ISSUE THREAD

**Issue by shlomiassaf** [telerik/nativescript-ui-samples-angular#26] opened 2016-08-13 04:49 UTC
Hi,

Created an app with 2 routes pointing at the same component.

First route setup is `/`
2nd route setup is `feed` (same component as in route 1)

The component has a drawer with a button that opens it, showOverNavigation is set to true.

When entering the app and tapping the button drawer opens below the ActionBar.
The drawer has a link to the 2nd route, clicking on it.
In 2nd route, tapping on the button opens the drawer **above** the ActionBar as expected.

More info:
On bootstrap: `startPageActionBarHidden: false`

Template structure:
**Root component**

```
<ActionBar title="">
 <!-- content... -->
</ActionBar>
<page-router-outlet></page-router-outlet>
```

**Page Component**

```
<RadSideDrawer #drawerComponent showOverNavigation="{{true}}">
    <StackLayout tkDrawerContent>
        <StackLayout class="drawer-header">
            <Label text="Menu"></Label>
        </StackLayout>
        <ScrollView class="drawer-content">
            <StackLayout class="drawer-links" orientation="vertical">
                <StackLayout class="drawer-link"
                             orientation="horizontal">
                    <Button [nsRouterLink]="['/']" text="Home"></Button>
                </StackLayout>
                <StackLayout class="drawer-link"
                             orientation="horizontal">
                    <Button [nsRouterLink]="['/feed']" text="FEED"></Button>
                </StackLayout>
            </StackLayout>
        </ScrollView>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label text="Hello World"></Label>
        <Button (tap)="drawerComponent.sideDrawer.toggleDrawerState()">TAP</Button>
    </StackLayout>
</RadSideDrawer>
```

Can't seem to get the home page of the app to show drawer on top of ActionBar.

Thanks!

**Comment by VladimirAmiorkov** [comment] 2016-08-15 09:01
Hi @shlomiassaf ,

The `showOverNavigation` is currently not available in Angular {N} applications. As this feature proved to be an hard and interesting feature :) to implement and the final result was an good one but it involved implementing a new Page ([DrawerPage](http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started#showing-radsidedrawer-over-the-navigation-baraction-bar)) in order to be able to achieve the desired behavior. In the current (0.3.0) [nativescript-angular](https://www.npmjs.com/package/nativescript-angular) version changing the `Page` in which the angular Components  are placed is not available which directly means the `showOverNavigation` feature is not available. You can track [this](https://github.com/NativeScript/nativescript-angular/issues/394) feature request for future updates on this matter.

We are already looking into ways of providing this feature in the Angular {N} version of RadSideDrawer so stay tuned.

**Comment by mostafa-raafat** [comment] 2016-08-17 13:58
how can i use showOverNavigation ?

**Comment by VladimirAmiorkov** [comment] 2016-08-17 14:37
@mostafa-raafat As stated by my previous response https://github.com/telerik/nativescript-ui-samples-angular/issues/26#issuecomment-239758221 in the current (0.3.0) nativescript-angular and (1.3.1) nativescriptltelerik-ui versions the `showOverNavigation` is not supported. For more details on why please refer the mentioned comment. We will do our best to provide this functionality in Angular {N} as soon possible.

**Comment by hpstuff** [comment] 2016-08-26 11:56
I use workaround for iOS by accessing the native module method attachDrawerToWindow(), this method is used to put the drawer over navigation bar 
Just some enhancements on this example.
https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/getting-started/getting-started.component.ts
```
<RadSideDrawer #drawer showOverNavigation="true" (loaded)="load()">
...
</RadSideDrawer>
```
```
...
load() {
    this.drawerComponent.sideDrawer.ios.attachDrawerToWindow();
}
```

**Comment by dondragon2** [comment] 2016-08-26 13:51
@hpstuff How would this work for Android though?

**Comment by chief10** [comment] 2016-08-30 19:23
+1 on getting this to work on Android + Angular

**Comment by denkomanceski** [comment] 2016-09-18 11:36
Any progress on this ?

**Comment by VladimirAmiorkov** [comment] 2016-09-18 12:21
Hi @denkomanceski ,

You can follow [this](https://github.com/NativeScript/nativescript-angular/issues/394) issue from the nativescript-angular repo for future updates. As previously mentioned in order for the "over navigation bar" feature to be available in {N} + Angular 2 the Page (which is currently internally managed and created by the nativescript-angular renderer) needs to be exposed so it can be replaced with our DrawerPage.

**Comment by denkomanceski** [comment] 2016-09-18 21:23
Okay Vladimir, thank

**Comment by pavankumarkatakam** [comment] 2016-10-17 15:50
Is there any progress on this?

**Comment by NgSculptor** [comment] 2016-11-11 20:13
@VladimirAmiorkov setting `showOverNavigation` seems to be working on IOS but not android, is it still in the works with `"nativescript-telerik-ui-pro": "^1.4.1"` ?

**Comment by VladimirAmiorkov** [comment] 2016-11-12 09:26
Hi @NgSculptor ,

Yes the "showOverNavigation" feature is still being developed for both iOS and Android. While it is possible to set the showOverNavigation property and make it look like it is working correctly on iOS with 1.4.1 it is not really supported that in that version and may lead to some unexpected behaviors. For the Android portion of this feature it is a little more complex scenario due to the Android UI trees but we are doing our best to bring this feature to live in {N} + Angular.

**Comment by jamieathans** [comment] 2017-01-09 05:55
Hello,

As [[Feature] Provide a way to replace the default 'Page' with a custom instance #394](https://github.com/NativeScript/nativescript-angular/issues/394) has been merged (which this issues seems to depend on), any more progress on resolving this issue?

**Comment by VladimirAmiorkov** [comment] 2017-01-09 09:02
@jamieathans This feature request is still open, we will do our best to include it in once of our next releases of nativescript-telerik-ui

**Comment by jamieathans** [comment] 2017-01-11 00:02
@VladimirAmiorkov Good to hear this is still coming in a future release.

It may not seem like a big deal, but it makes apps built with NativeScript seem "different" from the norm. Potential clients will ask "Why doesn't the the side menu look like the one in Google Maps ...".

Are the any hacks or work arounds I can apply at the moment to expose a DrawPage in Angular to get this working before the official fix?

**Comment by VladimirAmiorkov** [comment] 2017-01-11 10:45
@jamieathans Unfortunately this feature is not a simple to implement as it might looks like due to the way Android and NativeScript both manage an UI tree and in this case Angular's rendered also which makes it that three different UI tree management systems are "arguing" how to render the Page, its ActionBar, content and RadSideDrawer. This is why a workaround is simply impossible without a custom UI tree management implementation etc.

We are aware of the demand of this feature in Angular and we will do our best to implement it as soon as possible.

**Comment by ntrp** [comment] 2017-01-24 20:11
It was working in android before, I don't understand why now it is not possible anymore, did the nativescript-angular project change?

Anyway this feature is really important from my point of view, it's one of the features that make nativescript(-angular) not yet ready for production.

Not trying to complain because I know it is pretty complicate and it is an open source project but just wanted to point that out. I would love to use it to build an app but every time I start I find something like this :(

**Comment by x00** [comment] 2017-02-11 16:24
I suppose you could create a dummy action bar and overlap that

**Comment by miroslavaivanova** [comment] 2017-03-08 12:07
I will move this issue to the dedicated GitHub repository for NativeScript UI issues (as this one contains examples only): https://github.com/telerik/nativescript-ui-feedback.
If you have any feedback, issues or feature requests please log them in nativescript-ui-feedback repository.

Thanks for your understanding!

**Closed by miroslavaivanova** 2017-03-08 12:07 UTC
Labels: feature
