### ISSUE TITLE
inlineEventSelectedEvent will not be fire for iOS

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-samples-angular#28] opened 2016-08-31 14:34 UTC
`inlineEventSelected`  event will not be fire in case you would like to get the data for the selected event from the ListView inside the RadCalendar for iOS.

HTML Code:

```
<ActionBar title="Events view modes">
    <NavigationButton text="Back" icon="res://ic_arrow_back_black_24dp" (tap)="onNavigationButtonTap()"></NavigationButton>
    <ActionItem text="Options" ios.position="right" (tap)="onOptionsTapped()"></ActionItem>
</ActionBar>
<StackLayout>
    <RadCalendar id="calendar" (dateSelected)="onDateSelected($event)" 
                (inlineEventSelected)="inlineEvent($event)" [eventSource]="eventSource" [eventsViewMode]="eventsViewMode"></RadCalendar>
</StackLayout>
```

TypeScript Code

```
import { OptionsExampleBase } from "../../options-example-base";
import {Component, OnInit, Inject} from "@angular/core";
import { Router } from '@angular/router';
import {CalendarEventsService} from "../calendar-events.service";
import { OptionsService } from "../../navigation/options/options.service";
import calendarModule = require("nativescript-telerik-ui-pro/calendar");
import { Page } from "ui/page";
import * as applicationModule from "application";
import {CalendarInlineEventSelectedData, CalendarSelectionEventData} from "nativescript-telerik-ui-pro/calendar"

@Component({
    moduleId: module.id,
    selector: "calendar-events-view-modes",
    templateUrl: "calendar-events-view-modes.component.html",
    providers: [CalendarEventsService]
})

export class CalendarEventsViewModesComponent extends OptionsExampleBase implements OnInit {
    private _events: Array<calendarModule.CalendarEvent>;
    private _calendar: calendarModule.RadCalendar;
    private _optionsParamName: string;
    private _eventsViewMode;
    constructor( @Inject(Page) private _page: Page, private _calendarService: CalendarEventsService,
        private _optionsService: OptionsService, private _router: Router) {
        super();
        if (applicationModule.ios) {            
            this._page.on("navigatingTo", this.onNavigatingTo, this);
            this._optionsParamName = "eventsViewMode";
            this._optionsService.paramName = this._optionsParamName;
            this.router = _router;
            this.navigationParameters = { selectedIndex: 0, paramName: this._optionsParamName, items: ["None", "Inline", "Popover (iPad only)"] };
        }
        this._eventsViewMode = calendarModule.CalendarEventsViewMode.None;
    }
    
    get eventSource() {
        return this._events;
    }
    
    get eventsViewMode() {
        return this._eventsViewMode;
    }
    
    ngOnInit() {
        this._events = this._calendarService.getCalendarEvents();
        this._calendar = <calendarModule.RadCalendar>this._page.getViewById("calendar");
    }   
    
    onNoneTap() {
        this._eventsViewMode = calendarModule.CalendarEventsViewMode.None;
    }
    
    onInlineTap() {
        this._eventsViewMode = calendarModule.CalendarEventsViewMode.Inline;
    }
    
    onPopoverTap() {       
        this._eventsViewMode = calendarModule.CalendarEventsViewMode.Popover;
    }
    
     public onNavigatingTo(args) {
        if (args.isBackNavigation) {
            if (this._optionsService.paramName === this._optionsParamName) {
                switch (this._optionsService.paramValue) {
                    case "None":
                        this.onNoneTap();
                        this.navigationParameters.selectedIndex = 0;
                        break;
                    case "Inline":
                        this.onInlineTap();
                        this.navigationParameters.selectedIndex = 1;
                        break;
                    case "Popover":
                        if (UIDevice.currentDevice().userInterfaceIdiom === UIUserInterfaceIdiomPad) {
                            this.onPopoverTap();
                            this.navigationParameters.selectedIndex = 2;
                        }
                        break;
                    default:
                        break;
                }
            }
        }
    }

    public inlineEvent(args:CalendarInlineEventSelectedData){
        console.log("event "+args.eventData.title);
        
    }

    public onDateSelected(args: CalendarSelectionEventData) {
        console.log("date");
        console.log(args.eventName);
        console.log(args.date);
    }

}
```

CLI: 2.2.1
nativescript-telerik-ui-pro: 1.3.1
nativescript-angular: 0.3.0
tns-core-modules: 2.2.0

**Comment by VladimirAmiorkov** [comment] 2016-09-08 15:33
Its looks like this issue on android is caused by the initial value of the `eventsViewMode`. As a temporary workaround you can set it to `Inline` directly in the XML.

**Comment by mattgalvin** [comment] 2016-09-14 00:23
Thanks Vladimir, I'll give that a try (I reported this initially through the telerik forum). Any workaround for iOS - that's where I really need it since my dialog solution on Android to get around this really looked crappy on iOS.

**Comment by mattgalvin** [comment] 2016-09-14 00:42
First, I had the case wrong - I had "inline" in my code which still displays the events inline but no events get triggered. When I changed it to "Inline", the android event triggers as expected but the same code running in iOS does not trigger the event.

**Comment by VladimirAmiorkov** [comment] 2016-09-14 13:23
Hi @mattgalvin ,

We have already resolved this issue and it will be released in the next official release of [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro). You can expect the next release by the end of the this week.

**Comment by mattgalvin** [comment] 2016-09-14 13:55
Rock on!

**Comment by VladimirAmiorkov** [comment] 2016-09-16 14:12
Fixed in **1.4.0**

**Closed by VladimirAmiorkov** 2016-09-16 14:12 UTC
Labels: in progress

**Comment by mattgalvin** [comment] 2016-09-19 14:04
I confirmed that this is firing for iOS in 1.4.0. However, it no longer seems to be firing in Android. I understand that in the API documentation it does state iOS only (http://docs.telerik.com/devtools/nativescript-ui/api/classes/radcalendar.html#inlineeventselectedevent), however, with v1.3.1, it was working in Android.

Are there plans to support the inline event selected event on both platforms?

**Comment by mattgalvin** [comment] 2016-09-19 14:59
Hmm.. I'll see what I can figure out. I have tried deleting those with no success. It's actually a clean project created with the latest libraries from scratch and source code copied over so there never was an earlier version to have been cached. I'll post whatever I find back here in case anyone else runs into it. Thanks for the help.

**Comment by VladimirAmiorkov** [comment] 2016-09-20 06:58
@mattgalvin 

Thank you for sharing your findings. Indeed I was able to reproduce the issue when directly setting the eventsViewMode statically via the HTML rather than via Angular 2 binding. I have corrected this behavior and it should be fixed with our next release I apologize for the inconvenience. For now as a work around you can use the mentioned approach of settings the eventsViewMode through a binding.
