### ISSUE TITLE
Integrate strophe.js in nativescript 

### ISSUE THREAD

**Issue by rsrini83** [telerik/nativescript-ui-samples-angular#30] opened 2016-09-07 09:37 UTC
Hi,

I tried to use xmpp javascript client in strophe.js in nativescript, but end up with different issues. Can we use this library in nativescript ? Or  If there are any library which can be used in nativescript then please tell me.

--Srini

**Comment by VladimirAmiorkov** [comment] 2016-09-07 15:12
Hi @rsrini83 ,

Using JS libraries in NativeScript is totally open and any appropriate library can be added via npm or manually. The question if and how that library might work with the NativeScript framework is a different question. If the specific library uses web only specifics and implementations then that framework might be incompatible with the NativeScript framework and may require some implementations specific to the native (iOS and/or Android) platforms that the NativeScript framework enables.

Could you give us some more details regarding what exactly the Strophe.js will be used in your {N} application and what errors does it throw when you run it?

**Comment by raosrinivas1983** [comment] 2016-09-07 15:23
Hi Valdimir,
Thanks for quick reply. Strophe.js is XMPP client in JavaScript. However it has tight couple with the web components like window, document and XMLHttpRequest objects. I have created few dummy objects and thought of verifying whether it is loading or not. Some reason it gives Strophe is undefined. But actually it is defined.

I tried other approach, used web-view to load this library. As i need bi-directional communication i tried to use nativescript-webview-interface in {N}-angular2. Unfortunately this plugin is not working in {N}-angular2 project. I root caused the issue (webview.android is undefined), but i don't know how to fix this issue also. 
If any suggestion is greatly helpful for my project. At the moment i don't have any way (Neither Webview or pure javascript).

--Srini

**Comment by VladimirAmiorkov** [comment] 2016-09-08 11:28
@raosrinivas1983 ,

Thank you for the additional information. I tested the mentioned JS library and it looks like it is incompatible with the NativeScript framework because as you mentioned it is coupled to web browser specifics (window, document etc.). The "output" of the NativeScript framework is a pure native (iOS or/and Android) application which means there is no window or document or any web browser specific element.

The only way of getting the Strophe.js library working in NativeScript would be to decouple it from the web browser specifics or polyfill it. You can take a look at the implementation of[this](https://github.com/NathanaelA/nativescript-websockets) {N} plugin which provides WebSockets.

Closing the issue.

**Closed by VladimirAmiorkov** 2016-09-08 11:28 UTC
Labels: needs more info, question

**Comment by samuelagm** [comment] 2016-11-19 21:38
This library [nativescript-xmpp-client](https://github.com/samuelagm/nativescript-xmpp-client) should work for you
