### ISSUE TITLE
Cannot find module 'nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives'

### ISSUE THREAD

**Issue by ngydat** [telerik/nativescript-ui-samples-angular#1] opened 2016-05-11 08:17 UTC
Hello,

Now that Nativescript UI can be used with Angular 2, I'm trying to put the sidedrawer. The problem is not about the code itself (it's very clear) but there is this line in this [file](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/getting-started/getting-started.component.ts) (this line can be found in other files too well at least the from part): 

`import {RadSideDrawerComponent, SideDrawerType, MainTemplateDirective, DrawerTemplateDirective} from "nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives";`

So when I put this line, the Typescript compiler tells me it cannot find the module. Am I missing anything ?

Thank you in advance

Edit : I think the problem comes from the fact that the definition type file (a file with d.ts as the extension) is missing

**Comment by nickcoury** [comment] 2016-05-13 07:18
I'm having the same issue.  I assume it was built with the original .ts files, but since the plugin only includes the compiled .js for Angular 2 without any Typescript definitions, it won't work.  I can get it to manually work by shimming the information by hand, but it would be nice to have the Typescript defs included like the non-Angular files.

**Comment by nickcoury** [comment] 2016-05-13 08:53
Here's the shim I'm currently using, until we can get the official definition files.  Place this in the nativescript-telerik-ui/sidedrawer/angular/ folder in side-drawer-directives.d.ts, and add the fields you use as needed:

export class RadSideDrawerComponent {
    sideDrawer: any;
}
export class SideDrawerType {
    showDrawer(): any;
}
export class MainTemplateDirective {}
export class DrawerTemplateDirective {}

**Comment by Gagoo** [comment] 2016-05-17 04:08
Hello,

I'm experimenting the same issue.
No way to get this side-drawer-directives.d.ts file.
Would someone at Telerik help us ? :)

Thx :)

**Comment by VladimirAmiorkov** [comment] 2016-05-18 06:48
Hi,

We have reviewed this issue and we are already working on resolving it in our next release of Telerik UI for NativeScript.

**Comment by lazar-vuckovic** [comment] 2016-05-25 10:40
Any update on when this will be tackled?
Thanks

**Comment by VladimirAmiorkov** [comment] 2016-05-25 12:45
Hi @lazar-vuckovic ,

We have resolved this issue and it is currently being internally tested. All of the type definition files for the nativescript-telerik-ui angular directives will be available in our next official release of [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) and [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro).

In the mean while you can resolve both this and the [other](https://github.com/telerik/nativescript-ui-samples-angular/issues/2) logged issue by manually creating the missing type definition (d.ts) files in the 'node_modules/nativescript-telerik-ui/sidedrawer/angular folder'. You can use [this gist](https://gist.github.com/VladimirAmiorkov/ade19d30a2ad2641c9213694db340a27) to manually create the required [index.d.ts](https://gist.github.com/VladimirAmiorkov/ade19d30a2ad2641c9213694db340a27#file-index-d-ts) and [package.json](https://gist.github.com/VladimirAmiorkov/ade19d30a2ad2641c9213694db340a27#file-package-json) files. Regarding the ListView issue you can use [this gist](https://gist.github.com/VladimirAmiorkov/bfcd0c87f5349399718e36dcfe4e07bc).

**Comment by lazar-vuckovic** [comment] 2016-05-25 13:28
Thanks for the quick response.
Looking forward to the new ui-pro release.

**Comment by farajfarook** [comment] 2016-06-03 12:06
When will you release the next version with this fixed. I'm actually waiting for 2 weeks. 

Another issue is that current nativescript-telerik-ui is depending on angular 2 beta not the angular 2 rc. Will it be fixed as well?

**Comment by VladimirAmiorkov** [comment] 2016-06-03 14:16
Hi @farajfarook ,

The next release of [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) and [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) is expected to be out by the end of the month (June). 

We are already working on moving the Angular 2 support to the latest RC (2.0.0-rc.1) and those fixes are also planned to be included in the next release.

**Comment by echap** [comment] 2016-06-06 14:54
@VladimirAmiorkov I've been using your fix, i.e.
1. `tns plugin add nativescript-telerik-ui`
2. in `<project>/node_modules/nativescript-telerik-ui/sidedrawer/angular`, I added two files, `index.d.ts` and `package.json`
3.```
/* index.d.ts */
import {
    TemplateRef,
    ElementRef,
    EventEmitter
} from "angular2/core";
import {View} from "ui/core/view";
import * as SideDrawerModule from './../';

export type SideDrawerType = SideDrawerModule.RadSideDrawer & View & {toggleDrawerState: () => void}

/**
 * This is the SideDrawer component. It separates your mobile app's screen
 * into a main part and a menu part whereby the menu part is shown upon a swipe
 * gesture using a transition effect.
 */
export class RadSideDrawerComponent {

    /**
     * The presented RadSideDrawer.
     */
    sideDrawer: SideDrawerType;

    /**
     * Gets or sets the main screen content for the current SideDrawer instance.
     */
    mainTemplate: TemplateRef;

    /**
     * Gets or sets the menu screen content for the current SideDrawer instance.
     */
    drawerTemplate: TemplateRef;

    /**
     * The transition used to animate the process of showing or hiding
     * the menu pane. Depending on the transition set, the main content can also be part of
     * the animation.
     */
    transition: SideDrawerModule.DrawerTransitionBase;

    /**
     * Defines either the width or the height
     * of the menu pane depending on the location of the SideDrawer.
     * Top or Bottom - height, Right or Left - width.
     */
    drawerContentSize: number;

    /**
     * Indicates whether the RadSideDrawer is shown over the navigation bar.
     */
    showOverNavigation: boolean;

    /**
     * Gets or sets a boolean value that determines if drawer can be opened or closed with gestures.
     */
    gesturesEnabled: boolean;

    /**
     * Identifies the {@link drawerTransition} property.
     */
    drawerTransition: string;

    /**
     * Identifies the {@link drawerLocation} property.
     */
    drawerLocation: string;
}

/**
 * Directive identifying the main template.
 */
export class MainTemplateDirective {

}

/**
 * Directive identifying the drawer template.
 */
export class DrawerTemplateDirective {

}

/**
 * Directives identifying the RadSideDrawer.
 */
export const SIDEDRAWER_DIRECTIVES;

/**
 * Providers used by the identifying RadSideDrawerComponent.
 */
export const SIDEDRAWER_PROVIDERS;
```
```
/* package.json */
{
  "name" : "side-drawer-directives",
  "main" : "side-drawer-directives.js »
}```
3. Adding the line in file `<projectroot>/reference.d.ts`
```/// <reference path="./node_modules/nativescript-telerik-ui/sidedrawer/index.d.ts" />```

**Comment by echap** [comment] 2016-06-06 14:57
Question is : what am I missing ? ><

**Comment by getmetorajesh** [comment] 2016-06-08 01:05
I got rid of the compilation error following the above steps with exception of step 4. 
instead of 
step 4. `import {SIDEDRAWER_PROVIDERS} from "nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives" `

I used, 

4. `import {SIDEDRAWER_PROVIDERS} from "nativescript-telerik-ui/sidedrawer/angular"`

Now I am getting `nativescript-telerik-ui/sidedrawer/angular/index.d.ts(27,19): error TS2314: Generic type 'TemplateRef<C>' requires 1 type argument(s).` from the added `index.d.ts file` when trying to compile

**Comment by VladimirAmiorkov** [comment] 2016-06-08 07:39
Hi @getmetorajesh ,

It looks like you are using the Angualr 2 RC (2.0.0-rc.1) version which has made couple of breaking changes one of which is that the TemplateRef **now requires** an type (TemplateRef<any>). The current version (1.1.1) of [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) and [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) was developed while angular was still in its beta and is not comparable with Angualr 2.0.0-rc.1. As [mentioned earlier](https://github.com/telerik/nativescript-ui-samples-angular/issues/1#issuecomment-223590570) we are already working on moving the nativescript-telerik-ui to the latest Angular RC and it will be available later this month. 

The workaround [gist](https://gist.github.com/VladimirAmiorkov/ade19d30a2ad2641c9213694db340a27) that I posted earlier was created to be used with the **2.0.0-beta.14** which is why using it with the 2.0.0-rc.1 would cause errors.

**Comment by rcluan** [comment] 2016-06-14 00:35
@getmetorajesh regarding the `TemplateRef<C>` issue, try to replace `TemplateRef `at `mainTemplate` with `mainTemplate : TemplateRef<MainTemplateDirective>` and do the same to `drawerTemplate` using `DrawerTemplateDirective`. I haven't got any compilations errors using this approach so far haha. However, I'm still getting an annoying error of "Cannot read property 'android' from undefined". Does @VladimirAmiorkov know how to solve this? Cheers =)

**Comment by VladimirAmiorkov** [comment] 2016-06-14 06:35
@rcluan Can you share the full log when you get the mentioned 

> Cannot read property 'android' from undefined

error so I could take a closer look?

**Comment by rcluan** [comment] 2016-06-14 17:14
@VladimirAmiorkov here it goes

> Found peer TypeScript 1.8.10
JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE.
JS: EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
JS: STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'android' of u
ndefined
JS: at resolvePromise (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
JS: at /data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:473:14
JS: at ZoneDelegate.invoke (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
JS: at Object.NgZoneImpl.inner.inner.fork.onInvoke (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
JS: at ZoneDelegate.invoke (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:280:35)
JS: at Zone.run (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:174:44)
JS: at /data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:529:58
JS: at ZoneDelegate.invokeTask (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:314:38)
JS: at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:36:41)
JS: at ZoneDelegate.invokeTask (/data/data/org.nativescript.PersonalGym/files/app/tns_modules/zone.js/dist/zone-node.js:313:43)
JS: Unhandled Promise rejection: Cannot read property 'android' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'android' of undefined
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
13:52:52 - Compilation complete. Watching for file changes.

I'm using ns+ng2 and the html template provided on [http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started](url)
The only thing I changed on the template was the tap function of the drawerMain's button.

**Comment by rlaurente** [comment] 2016-06-19 16:35
Hi any news on this ?

**Comment by VladimirAmiorkov** [comment] 2016-06-20 06:22
@rcluan 

After looking the call stack it looks like you are using the [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) version 1.1.1 with either the RC1 or RC2 of angular. Please note that the nativescript-telerik-ui version 1.1.1 was developed before the RC1 or RC2  versions of angular was available which is why they are not compatible. 

As mentioned [earlier](https://github.com/telerik/nativescript-ui-samples-angular/issues/1#issuecomment-223590570) we are in the process of releasing an update in the next couple of days which will be compatible with the RC1 of angular followed by an update for the RC2.

**Comment by rcluan** [comment] 2016-06-20 14:51
@VladimirAmiorkov 

Thank you. I'm looking forward for this update. Cheers

**Comment by rlaurente** [comment] 2016-06-22 03:20
@VladimirAmiorkov 

I was able to implement this sidedrawer by using the getting started codebase.
It's working fine but I want sidedrawer to overlap the actionbar when it shows just like gmail and playstore.

Please refer to screenshot below.

![screenshot_2016-06-22-11-15-01](https://cloud.githubusercontent.com/assets/1804380/16253695/34b89308-386b-11e6-8dc2-be4fc49a6956.jpg)
![screenshot_2016-06-22-11-15-21](https://cloud.githubusercontent.com/assets/1804380/16253696/34f0fe82-386b-11e6-9c5a-d5fccc7e699f.jpg)

**Comment by VladimirAmiorkov** [comment] 2016-06-22 07:05
Hi @rlaurente ,

As your question is not related to this issue I suggest you to post it in our forums [here](http://www.telerik.com/forums/nativescript-ui/sidedrawer) where you can also find many useful threads about [all of the components](http://www.telerik.com/forums/nativescript-ui) in the nativescript-telerik-ui suite.

**Comment by ginev** [comment] 2016-06-22 07:07
Hello @rlaurente,
this is on our TODO list. Truth is, this was supposed to be released earlier but it proved to be a real challenge to implement. We will keep you updated on this as soon as its done. Please, refer to my colleague @VladimirAmiorkov for posting on the product forums for better visibility.

**Comment by VladimirAmiorkov** [comment] 2016-07-04 12:19
Fixed with [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) **1.2.0**

**Closed by VladimirAmiorkov** 2016-07-04 12:19 UTC

**Comment by rsrini83** [comment] 2016-08-29 18:02
Hi Vladimir,
I know this issue is closed but would like to ask a question as i'm facing issue and was not able to solve it. I have a listview and sidedrawer in the page, When the sidedrawer is opened, its content is behind the listview elements (i.e listview z-index is higher than sidedrawer). Can you please guide how to fix this issue ?
I'm using nativescript-angular (grocery example).  Thanks in advance.

Below is content from the view,

<AbsoluteLayout>
    <RadSideDrawer #drawer left="0" top="47" style="z-index:50000">
            <StackLayout tkDrawerContent class="sideStackLayout" style="z-index:50000" >
                <StackLayout class="sideTitleStackLayout">
                    <Label text="Navigation Menu"></Label>
                </StackLayout>
                <StackLayout class="sideStackLayout">
                    <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
                    <Label text="Social" class="sideLabel"></Label>
                    <Label text="Promotions" class="sideLabel"></Label>
                    <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
                    <Label text="Important" class="sideLabel"></Label>
                    <Label text="Starred" class="sideLabel"></Label>
                    <Label text="Sent Mail" class="sideLabel"></Label>
                    <Label text="Drafts" class="sideLabel"></Label>
                </StackLayout>
            </StackLayout>
            
    </RadSideDrawer>
  </AbsoluteLayout>
<GridLayout #container rows="44, *">
  <Label
		  row="0"
		  col="1"
		  class="fa side-menu-icon"
		  [text]="'fa-bars' | fonticon" 
		  (tap) = "openDrawer()"></Label>     
<GroceryList
  [row]="1"
  (loading)="showActivityIndicator()"
  (loaded)="hideActivityIndicator()"
  [showDeleted]="isShowingRecent"></GroceryList>
<ActivityIndicator
  [busy]="isLoading"
  row="1"></ActivityIndicator>
</GridLayout>

**Comment by VladimirAmiorkov** [comment] 2016-08-30 14:32
@rsrini83 ,

I am not sure what the issue you are experiencing is. I tried to reproduce it to no avail using the LIstView's [getting-started](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/getting-started) and SideDrawer's [getting-started](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/sidedrawer/getting-started) examples. The final result looks something like this:

html:
```
<RadSideDrawer #drawer>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>
        <RadListView [items]="dataItems" height="300">
            <template tkListItemTemplate let-item="item">
                <StackLayout orientation="vertical">
                    <Label class="nameLabel" [text]="item.name"></Label>
                    <Label class="descriptionLabel" [text]="item.description"></Label>
                </StackLayout>
            </template>
        </RadListView>
    </StackLayout>
</RadSideDrawer>
```

the Component code:
```
import { Component, ElementRef, ViewChild, Injectable, OnInit, ChangeDetectorRef } from "@angular/core";
import { View } from "ui/core/view";
import { RadSideDrawer } from "nativescript-telerik-ui-pro/sidedrawer";
import { Page } from "ui/page";
import { ActionItem } from "ui/action-bar";
import sideDrawerModule = require('nativescript-telerik-ui-pro/sidedrawer');
import { Observable } from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui-pro/sidedrawer/angular";
import { DataItemService } from "../../listview/dataItem.service";
import { ObservableArray } from "data/observable-array";
import { DataItem } from "../../listview/dataItem";

@Component({
    moduleId: module.id,
    selector: "tk-sidedrawer-getting-started",
    providers: [DataItemService],
    templateUrl: 'getting-started.component.html',
    styleUrls: ['getting-started.component.css']
})
@Injectable()
export class SideDrawerGettingStartedComponent extends Observable implements OnInit {
    private _dataItems: ObservableArray<DataItem>;

    constructor(private page: Page, private _changeDetectionRef: ChangeDetectorRef, private _dataItemService: DataItemService) {
        super();
    }

    @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
    private drawer: SideDrawerType;

    ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
    }

    get dataItems(): ObservableArray<DataItem> {
        return this._dataItems;
    }

    ngOnInit() {
        this.set("mainContentText", "SideDrawer for NativeScript can be easily setup in the XML definition of your page by defining main- and drawer-content. The component"
            + " has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.");
        this._dataItems = new ObservableArray(this._dataItemService.getDataItems());

    }

    public openDrawer() {
        this.drawer.showDrawer();
    }
}
```

**Comment by rsrini83** [comment] 2016-08-30 14:50
@VladimirAmiorkov,

Thanks for your time and the example.  I understand after i go through your example carefully and the basic mistake i was doing is main content i placed outside the "RadSideDrawer" tag. Due to that it was not working, after i place my main content inside tkMainContent, then no issues.

**Comment by yazdkhasti** [comment] 2016-08-31 17:00
@VladimirAmiorkov,
I get this error:
 ORIGINAL EXCEPTION: TypeError: Cannot read property 'android' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'android' of undefined
JS:     at RadSideDrawer.initOldDrawer (/data/data/org.nativescript.TestApp/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:91:40)
JS:     at RadSideDrawer._createUI (/data/data/org.nativescript.TestApp/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:147:18)
JS:     at RadSideDrawer.View._onContextChanged (/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js:197:14)
JS:     at RadSideDrawer.View._onAttached (/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js:149:14)
JS:     at Page.View._addViewCore (/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view.js:125:18)
JS:     at Page.View._addView (/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/core/view-common.js:952:14)
JS:     at Page.Object.defineProperty.set [as content] (/data/data/org.nativescript.TestApp/files/app/tns_modules/ui/content-view/content-view.js:19:22)
JS:     at ViewUtil.insertChild (/data/data/org.nativescript.TestApp/files/app/tns_modules/nativescript-angular/view-util.js:56:28)
JS:     at ViewUtil.createAndAttach (/data/data/org.nativescript.TestApp/files/app/tns_modules/nativescript-angular/view-util.js:103:18)
JS:     at ViewUtil.createView (/data/data/org.nativescript.TestApp/files/app/tns_modules/nativescript-angular/view-util.js:110:25)

App Component:

import { Component, ElementRef, ViewChild, Injectable, OnInit, ChangeDetectorRef } from "@angular/core";
import { View } from "ui/core/view";
import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer";
import { Page } from "ui/page";
import { ActionItem } from "ui/action-bar";
import sideDrawerModule = require('nativescript-telerik-ui/sidedrawer');
import { Observable } from "data/observable";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";



@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
@Injectable()
export class AppComponent  implements OnInit {
  
 constructor(private page: Page, private _changeDetectionRef: ChangeDetectorRef) {
     
    }

  @ViewChild("drawer") public drawerComponent: RadSideDrawerComponent;
    private drawer: SideDrawerType;

    ngAfterViewInit() {
        this.drawer = this.drawerComponent.sideDrawer;
        this._changeDetectionRef.detectChanges();
    }

    ngOnInit() {
        // this.set("mainContentText", "SideDrawer for NativeScript can be easily setup in the XML definition of your page by defining main- and drawer-content. The component"
        //     + " has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.");
    }

    public openDrawer() {
        this.drawer.showDrawer();
    }
}

View:
<RadSideDrawer #drawer>
    <StackLayout tkDrawerContent>
       <StackLayout>
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout>
            <Label text="Primary"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
     <Label text="mainContentText" textWrap="true"></Label>
        <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>
    </StackLayout>
</RadSideDrawer>

Main:

import {nativeScriptBootstrap} from "nativescript-angular/application";
import { SIDEDRAWER_PROVIDERS } from "nativescript-telerik-ui/sidedrawer/angular";
import {AppComponent} from "./app.component";

nativeScriptBootstrap(AppComponent,[SIDEDRAWER_PROVIDERS]);


Package.json:

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.TestApp",
    "tns-android": {
      "version": "2.2.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "nativescript-angular": "^0.3.0",
    "nativescript-telerik-ui": "^1.3.1",
    "reflect-metadata": "^0.1.5",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "2.2.1",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "babel-traverse": "6.14.0",
    "babel-types": "6.14.0",
    "babylon": "6.9.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}

**Comment by VladimirAmiorkov** [comment] 2016-08-31 21:02
@yazdkhasti try clearing node_modules, lin and platform folders. Also can you try running the repos app and see if the issue perists?

**Comment by yazdkhasti** [comment] 2016-09-02 09:16
@VladimirAmiorkov thank you. clearing node_modules and and platform folders solved the problem

**Comment by IvRRimum** [comment] 2016-09-28 15:17
Hello, this stilll doesn't work.

```
  1 import { Component, ElementRef, ViewChild, Injectable, OnInit, ChangeDetectorRef } from "@angular/core";
  2 import { View } from "ui/core/view";
  3 import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer";
  4 import { Page } from "ui/page";
  5 import { ActionItem } from "ui/action-bar";
  6 import sideDrawerModule = require('nativescript-telerik-ui/sidedrawer');
  7 import { Observable } from "data/observable";
  8 import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";
  9 import { ObservableArray } from "data/observable-array";
 10 
 11 @Component({
 12     selector: "sideDrawer",
 13     templateUrl: 'views/sidedrawer/sidedrawer.template.html',
 14     styleUrls: ['views/sidedrawer/sidedrawer.style.css']
 15 })
 16 @Injectable()
 17 export class SideDrawer extends Observable implements OnInit {
 18     constructor(private page: Page, private _changeDetectionRef: ChangeDetectorRef) {
 19         super();
 20     }
 21 
 22     @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
 23     private drawer: SideDrawerType;
 24 
 25     ngAfterViewInit() {
 26         this.drawer = this.drawerComponent.sideDrawer;
 27         this._changeDetectionRef.detectChanges();
 28     }
 29 
 30     ngOnInit() {
 31         this.set("mainContentText", "SideDrawer for NativeScript can be easily setup in the XML definition of your page by defining main- and drawer-content. The component"
 32             + " has a default transition and position and also exposes notifications related to changes in its state. Swipe from left to open side drawer.");
 33 
 34     }
 35 
 36     public openDrawer() {
 37         this.drawer.showDrawer();
 38     }
 39 }
```

```
  1 <RadSideDrawer #drawer>
  2     <StackLayout tkDrawerContent class="sideStackLayout">
  3         <StackLayout class="sideTitleStackLayout">
  4             <Label text="Navigation Menu"></Label>
  5         </StackLayout>
  6         <StackLayout class="sideStackLayout">
  7             <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
  8             <Label text="Social" class="sideLabel"></Label>
  9             <Label text="Promotions" class="sideLabel"></Label>
 10             <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
 11             <Label text="Important" class="sideLabel"></Label>
 12             <Label text="Starred" class="sideLabel"></Label>
 13             <Label text="Sent Mail" class="sideLabel"></Label>
 14             <Label text="Drafts" class="sideLabel"></Label>
 15         </StackLayout>
 16     </StackLayout>
 17     <StackLayout tkMainContent>
 18         <Label text="mainContentText" textWrap="true" class="drawerContentText"></Label>
 19         <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>
 20     </StackLayout>
 21 </RadSideDrawer>
```

Error:
```
JS: EXCEPTION: Error in views/dashboard/dashboard.template.html:1:2 caused by: Cannot read property 'sideDrawer' of undefined
JS: ORIGINAL EXCEPTION: Cannot read property 'sideDrawer' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'sideDrawer' of undefined
JS:     at SideDrawer.ngAfterViewInit (/data/data/org.nativescript.test/files/app/views/sidedrawer/sidedrawer.component.js:14:43)
JS:     at DebugAppView._View_Dashboard0.detectChangesInternal (Dashboard.ngfactory.js:502:61)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9566:18)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9671:48)
JS:     at DebugAppView.AppView.detectViewChildrenChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9592:23)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9577:18)
JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9566:18)
JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9671:48)
JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9584:23)
JS:     at DebugAppView.AppView.detectChangesInternal (/data/data/org.nativescript.test/files/app/tns_modules/@angular/core/bundles/core.umd.js:9576:18)
JS: ERROR CONTEXT:

```

**Comment by IvRRimum** [comment] 2016-09-28 15:23
Following this guide works: http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started

**Comment by IvRRimum** [comment] 2016-09-28 15:23
```
import { SIDEDRAWER_DIRECTIVES } from "nativescript-telerik-ui/sidedrawer/angular";
```
Is the correct one.

**Comment by eleddie** [comment] 2016-10-14 14:41
I can't make it work... I don't find a working example/tutorial. Any help would be appreciated

**Comment by ignaciolarranaga** [comment] 2016-10-14 15:16
@eleddie what about this: http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started

**Comment by eleddie** [comment] 2016-10-14 15:47
Thanks for the reply. I tried it but it doesn't work..
I get this on the device:

`com.tns.NativeScriptException: 
Calling js method onCreateView failed`

`TypeError: Cannot read property 'android' of undefined
File: "/data/data/biz.negocioselectonicos.salesforce/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js, line: 91, column: 39`

And many other lines..

**Comment by IvRRimum** [comment] 2016-10-14 16:12
I actually got this working. Had to create a new app and follow
getting-started guide.

**Comment by VladimirAmiorkov** [comment] 2016-10-14 16:14
Make sure that you delete all the lib, node_modules and platforms folders before running the app

**Comment by eleddie** [comment] 2016-10-14 16:39
I did this:
`rm -r node_modules platforms`
`tns install`

But still not working.. I'll check something in a few minutes
