### ISSUE TITLE
RadListView (Android) -  header/footer style breaking on tab change (after unLoaded)

### ISSUE THREAD

**Issue by shripalsoni04** [telerik/nativescript-ui-samples-angular#15] opened 2016-07-07 19:23 UTC
When I use RadListView inside TabView, it is working properly when I go to adjacent tab and come back to the tab with RadListView, but when I come back from tabs other than adjacent tabs, header style is getting removed.

Please check below .gif showing the problem on android.
![nativescript-radlist-tab-bug](https://cloud.githubusercontent.com/assets/4411891/16665943/1146d94a-44a3-11e6-9d5b-f169bda7994f.gif).

I have created a sample project to show this issue. You can clone it from https://github.com/shripalsoni04/nativescript-radlistview-tab.

**Comment by ignaciolarranaga** [comment] 2016-07-13 20:51
I'm experiencing something similar with the RadSideDrawer, but essentially I lost the styles on the first evaluation of something, for example:

This doesn't work (it means the companies-title class is not applied):
<StackLayout *ngIf="!adding">
                    <Label [text]="('associate-company.companies' | translate) + ':'" class="companies-title"></Label>

But this works:
<StackLayout>
                    <Label [text]="('associate-company.companies' | translate) + ':'" class="companies-title"></Label>

Not able to reproduce it on an independant environment, I think it is some dependency difference but still unable to guess it.
Driving me crazy!

**Comment by VladimirAmiorkov** [comment] 2016-08-15 12:26
Hi @ignaciolarranaga I noticed you opened a new issue regarding the observed behavior in the SideDrawer `tkMainContent`. I responded to you in that issue https://github.com/telerik/nativescript-ui-samples-angular/issues/18

**Comment by VladimirAmiorkov** [comment] 2016-08-16 12:35
@shripalsoni04 

We managed to reproduce the described scenario and indeed it looks like there is an issue in the current version of RadListView when it is unloaded by the TabView container. We will do our best to resolve it as soon as possible

**Comment by VladimirAmiorkov** [comment] 2016-08-18 07:33
The fix for this issue is on track and is planned for release with nativescript-telerik-ui **1.4.0**

**Comment by VladimirAmiorkov** [comment] 2016-09-16 14:11
Fixed in **1.4.0**

**Closed by VladimirAmiorkov** 2016-09-16 14:11 UTC
Labels: Done
